name: Publish Node.js Package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        working-directory: ./.github/actions/local-action/
      - run: npm test
        working-directory: ./.github/actions/local-action/

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
        working-directory: ./.github/actions/local-action/
      - run: npm publish
        working-directory: ./.github/actions/local-action/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
